# Generated by Django 5.0.3 on 2024-04-03 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sauvegarde', '0002_question_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='question',
            name='question_text',
        ),
        migrations.RemoveField(
            model_name='sauvegarde',
            name='chemin',
        ),
        migrations.RemoveField(
            model_name='sauvegarde',
            name='date_creation',
        ),
        migrations.RemoveField(
            model_name='sauvegarde',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='sauvegarde',
            name='taille',
        ),
        migrations.AddField(
            model_name='sauvegarde',
            name='humidite',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
